import { Box, Typography, Paper, Divider, Button } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import { Link as RouterLink } from 'react-router-dom'

const sections = [
  {
    title: '1. Introduction',
    body: 'This Privacy Policy explains how Coop Vision ("we", "us", or "our") collects, uses, stores, and protects information when you use our poultry farm monitoring platform. By creating an account or using the platform, you agree to the practices described in this policy.',
  },
  {
    title: '2. Information We Collect',
    body: 'We collect the following categories of information to operate the platform:',
    list: [
      'Account information: your name, email address, password (stored in encrypted form), role, and the farm you are associated with.',
      'Farm and device data: farm details, coop configurations, camera metadata (name, RTSP address, status), and chicken flock records.',
      'Telemetry and detection data: sensor readings (temperature, humidity, and other environment metrics) and automated bird counts generated by computer vision analysis.',
      'Media: snapshots and video streams captured by connected cameras, including alert-triggered media, which may contain images of birds and the farm premises.',
      'Usage data: login events, session tokens, and audit records used to keep the platform secure.',
    ],
  },
  {
    title: '3. How We Use Your Information',
    body: 'The information we collect is used solely to operate and improve the platform, including:',
    list: [
      'Providing live camera feeds, real-time bird counts, environment analytics, alerts, and reports.',
      'Authenticating your account and enforcing role-based access permissions.',
      'Detecting and alerting on anomalies such as intruders, equipment failures, or unusual conditions.',
      'Generating aggregated statistics and projections for farm management.',
      'Maintaining security, diagnosing faults, and preventing abuse of the platform.',
    ],
  },
  {
    title: '4. Camera and Video Data',
    body: 'Cameras are added by authorized farm administrators and stream only to the network you control. Live video is delivered on demand — it is not continuously recorded for viewing. We may retain short alert-triggered clips and snapshots to support notifications and incident review. You are responsible for ensuring that the placement of cameras on your premises complies with applicable laws and the expectations of people present.',
  },
  {
    title: '5. Data Sharing',
    body: 'We do not sell, rent, or trade your personal or farm data. We share information only in the following limited circumstances:',
    list: [
      'Within your organization: data is scoped to your farm and visible only to users of that farm, and to the company super administrator for platform administration.',
      'Service providers: third parties that host our infrastructure (such as cloud or server hosting) process data on our behalf under confidentiality obligations.',
      'Legal requirements: if required by law, regulation, or legal process, we will disclose information as necessary.',
    ],
  },
  {
    title: '6. Data Retention',
    body: 'We retain information only as long as needed for the purposes described in this policy. Environment and detection data are retained for reporting periods you select. Alert media is retained for a limited period and then automatically deleted. When you delete a camera, coop, or farm, associated data is removed from active use. You may request deletion of your account and associated personal data at any time.',
  },
  {
    title: '7. Data Security',
    body: 'We take reasonable technical and organizational measures to protect your data, including:',
    list: [
      'Passwords stored using strong, one-way cryptographic hashing.',
      'Short-lived session tokens and role-based access control on every request.',
      'Data isolation between farms so users only access their own farm data.',
      'Rate limiting on sensitive endpoints to reduce abuse.',
      'Secure transmission of data between your browser and our servers.',
    ],
  },
  {
    title: '8. Cookies and Local Storage',
    body: 'The platform uses browser local storage and httpOnly cookies to keep you signed in and to remember your selected farm. We do not use cookies for advertising or cross-site tracking. Your session token is stored in your browser and cleared when you log out.',
  },
  {
    title: '9. Sign-In with Google',
    body: 'If you choose to sign in with Google, we receive your email address and profile name from Google solely to create and identify your account. Google\u2019s handling of your data is governed by Google\u2019s own privacy policy. You may sign in with an email and password instead if you prefer.',
  },
  {
    title: '10. Your Rights',
    body: 'Depending on your jurisdiction, you may have the right to:',
    list: [
      'Access the personal data we hold about you.',
      'Request correction of inaccurate or incomplete data.',
      'Request deletion of your personal data and account.',
      'Object to or restrict certain processing activities.',
      'Export a copy of your farm data.',
    ],
    body2: 'To exercise any of these rights, contact your farm administrator or email us at the address below. You can also request account and data deletion directly from within the app via Settings > Delete Account & Data. We will respond within a reasonable time.',
  },
  {
    title: '11. Children\u2019s Privacy',
    body: 'The platform is intended for use by farm operators, managers, and administrators and is not directed to children under the age of 16. We do not knowingly collect personal information from children.',
  },
  {
    title: '12. Changes to This Policy',
    body: 'We may update this Privacy Policy from time to time to reflect changes in our practices or applicable law. We will notify you of material changes through the platform. The date at the top of this page indicates when the policy was last revised. Continued use of the platform after changes are posted constitutes acceptance of the updated policy.',
  },
  {
    title: '13. Contact Us',
    body: 'If you have questions or concerns about this Privacy Policy or how your data is handled, please contact us at abhishek@tvssecurity.com.',
  },
]

export default function PrivacyPolicy() {
  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#f8fafc', py: { xs: 4, md: 8 }, px: { xs: 2, sm: 4, md: 6 } }}>
      <Box sx={{ maxWidth: '860px', mx: 'auto' }}>
        <Button
          component={RouterLink}
          to="/"
          startIcon={<ArrowBackIcon />}
          sx={{ textTransform: 'none', color: '#0d3c3d', fontWeight: 600, mb: 3, alignSelf: 'flex-start' }}
        >
          Back to Sign In
        </Button>

        <Box sx={{ mb: 4, display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <Box component="img" src="/tvs_logo.png" alt="Coop Vision Logo" sx={{ height: 44, width: 'auto', objectFit: 'contain', borderRadius: 1 }} />
          <Typography
            variant="h5"
            sx={{ fontWeight: 800, fontFamily: '"Outfit", sans-serif', color: '#0d3c3d', letterSpacing: '0.06em' }}
          >
            COOP VISION
          </Typography>
        </Box>

        <Typography
          variant="h3"
          sx={{
            fontWeight: 700,
            fontFamily: '"Outfit", sans-serif',
            color: '#0f172a',
            letterSpacing: '-0.02em',
            fontSize: { xs: '1.8rem', md: '2.25rem' },
            mb: 1,
          }}
        >
          Privacy Policy
        </Typography>
        <Typography variant="body2" sx={{ color: '#64748b', fontWeight: 500, mb: 5 }}>
          Last updated: July 31, 2026
        </Typography>

        <Paper
          elevation={0}
          sx={{
            bgcolor: '#ffffff',
            border: '1px solid #e2e8f0',
            borderRadius: '16px',
            p: { xs: 2.5, md: 4 },
            mb: 4,
          }}
        >
          {sections.map((section, idx) => (
            <Box key={section.title}>
              <Typography
                variant="h6"
                sx={{ fontWeight: 700, fontFamily: '"Outfit", sans-serif', color: '#0f172a', mb: 1, fontSize: '1.05rem' }}
              >
                {section.title}
              </Typography>
              <Typography variant="body2" sx={{ color: '#475569', lineHeight: 1.7, mb: section.list ? 1.5 : 0 }}>
                {section.body}
              </Typography>
              {section.list && (
                <Box component="ul" sx={{ m: 0, pl: 3, mb: 2 }}>
                  {section.list.map((item) => (
                    <Box component="li" key={item} sx={{ color: '#475569', fontSize: '0.875rem', lineHeight: 1.7 }}>
                      {item}
                    </Box>
                  ))}
                </Box>
              )}
              {section.body2 && (
                <Typography variant="body2" sx={{ color: '#475569', lineHeight: 1.7, mb: 0 }}>
                  {section.body2}
                </Typography>
              )}
              {idx < sections.length - 1 && <Divider sx={{ my: 3, borderColor: '#f1f5f9' }} />}
            </Box>
          ))}
        </Paper>

        <Typography variant="caption" sx={{ color: '#94a3b8', display: 'block', textAlign: 'center' }}>
          &copy; {new Date().getFullYear()} Coop Vision. All rights reserved.
        </Typography>
      </Box>
    </Box>
  )
}
